version: '3'

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    volumes:
      - ${SOURCE_CODE_PATH_HOST}:${SOURCE_CODE_PATH_CONTAINER}
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/logs:/var/log/nginx
    ports:
      - ${NGINX_PORT}:80
      - 443:443
      - ${REVERB_PORT}:8080

    depends_on:
      - app
  app:
    container_name: app
    restart: always
    build:
      context: ./php-fpm
      args:
        - tag=${PHP_VERSION}
        - SOURCE_CODE_PATH_CONTAINER=${SOURCE_CODE_PATH_CONTAINER}
    volumes:
      - ${SOURCE_CODE_PATH_HOST}:${SOURCE_CODE_PATH_CONTAINER}
      - ./php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: ${SOURCE_CODE_PATH_CONTAINER}
    ports:
      - ${VITE_PORT}:5173
    expose:
      - 8080
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
